---
name: VyOS 1.3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * SAT'

jobs:
  build-iso:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    container:
      image: vyos/vyos-build:equuleus
      env:
        TZ: Australia/Brisbane
      options: --privileged

    steps:
      - name: Clone vyos-build repository
        run: |
          set -eux
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build
      - name: Get version number
        working-directory: vyos-build
        run: |
          echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Checkout to latest tag
        working-directory: vyos-build
        run: |
          set -eux
          git checkout tags/${{ env.RELEASE_VERSION }}
      - name: Configure build
        working-directory: vyos-build
        run: |
          set -eux
          ./configure --architecture amd64 --build-by matthew@tech.bymatt.au --build-type release --version ${{ env.RELEASE_VERSION }}
      - name: Build ISO
        working-directory: vyos-build
        run: |
          set -eux
          make iso
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "VyOS ${{ env.RELEASE_VERSION }}"
          tag: "${{ env.RELEASE_VERSION }}"
          artifacts: "vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso"
          artifactContentType: application/x-iso9660-image
          draft: true
          allowUpdates: true
          omitDraftDuringUpdate: true
